%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%                                                                     %%%
%%%                   TMAZE BEHAVIOR CHI SQUARE TEST                    %%%
%%%                                                                     %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Perform chi square goodness of fit test on Tmaze behavioral data. The
% input data is generated by the script Behavior_GenData.

% The behavioral data includes free choice trials only (no forced/blocked
% trials), and bad trials (eg runbacks) have been removed.

% As suggested by MvdM, "expected values should use the idea that if food/water
% restriction does not make a difference, the ratio of left/right trials
% should be the same for food/water. so say you had 10 left and 20 right
% trials in total, then you have a 1:2 ratio... so for 15 food restrict
% trials you would expect those to be 5 left, 10 right."

% Note that the important ways to group the trials for the chi square test are:
% 1. Number of left trials in total (including all lefts on food and water
%    restriction days)
% 2. Number of right trials in total
% 3. Number of trials performed on food restriction days (these include any
%    left and right trials when the rat was food restricted)
% 4. Number of trials performed on water restriction days

%       Food restriction days                    Water restriction days
%   nLeft trials      nRight trials         nLeft trials      nRight trials

% 1. nLeft trials on food days + nLeft trials on water days
% 2. nRight trials on food days + nRight trials on water days
% 3. nLeft trials on food days + nRight trials on food days
% 4. nLeft trials on water days + nRight trials on water days

% aacarey Sept 2015

clear

%% WHAT DO YOU WANT THIS SCRIPT TO DO?

% What to load and where to find it
cfg.input_fn = 'behavior'; % the script knows the proper file extension (.mat) so don't put it here
cfg.input_fd = 'D:\My_Documents\TmazePaper\data';

% What to call the output and where to save it
cfg.output_fn = 'behaviorChiSquareTest'; % it saves as a .txt
cfg.output_fd = 'D:\My_Documents\TmazePaper\data';

% Do you want to save the results?
cfg.writeDiary = 1; % keep a record of command window history; for this script, this is the results of the chi square test

%% Set up the things and do the thing

if cfg.writeDiary
        cd(cfg.output_fd)
        diary([cfg.output_fn,'.txt'])
        cd(cfg.output_fd)
end

iWasHere = pwd; % remember where I started 

rats = {'all','R042','R044','R050','R064'};

% load the behav struct
cd(cfg.input_fd)
load(cfg.input_fn)

% talk to me
disp(' '); disp('%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%')
disp(datestr(now))
disp('    The following data includes these rats:')
disp(rats)
disp('%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%')

for iRat = 1:length(rats)
    disp('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'); disp(['Data for ',rats{iRat},':'])
    disp('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'); disp(' ')
    
    temp = behav.(rats{iRat}); % because I don't want to type as much down there
    
    % [nleft on food day, nright on food day, nleft on water day, nright on water day]
    obs = [temp.food.nL temp.food.nR temp.water.nL temp.water.nR]; % the observed, real data
    
    nFood = obs(1) + obs(2); % total number of food day trials. could also do temp.nFood
    nWater = obs(3) + obs(4); % total number of water day trials
    ratioL = (obs(1)+obs(3)) / sum(obs); % ratio of L trials compared to total trials
    ratioR = (obs(2)+obs(4)) / sum(obs); % ratio of R trials
    
    exp = [nFood*ratioL nFood*ratioR nWater*ratioL nWater*ratioR]; % the "expected" values
    
    bins = 0:3;
    edges = -0.5:3.5;
    [h,p,stats] = chi2gof(bins,'Alpha',0.01,'Edges',edges,'freq',obs,'expected',exp,'Emin',1) % no semicolon b/c want to see output
    
end

%% finish up
if cfg.writeDiary; diary off; end
cd(iWasHere)