%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%                                                                     %%%
%%%              COUNT NUMBER OF Left/Right PLACE CELLS                 %%%
%%%                                                                     %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% For Tmaze data

% ABOUT
% This script loads the armPC file found in the files subfolder for each
% rat session. The armPC file is generated by a modified version of the
% CoOccur stuff.
% This script counts the number of left-only and right-only place cells for
% each session, and the totals for each rat and for all rats overall.
% It prints text to the command window and saves it in a text file, using
% MATLAB's diary function, for quick reference if needed. The text file is 
% saved in the same directory as the data.
%
% The base filename for this script's output is 'nPlaceCellsLR'.
%
% Generates and saves a variable called nPC which has the following
% organization:
%
% nPC.R042.s1.L = nLeftCells;
% nPC.R042.s1.R = nRightCells;
% nPC.R042.s1.sessionID = sessionID;  if needed for future reference
% nPC.R042.s2...     and so on for each session (s1-s6)
% nPC.R042.total.L = all left cells ever for this rat
% and so on for each rat
% nPC.TotalAllRats.L = all left cells for whole exp
%
% To generate a table in LaTeX speak, run the script nPlaceCellsLR_LaTeX_table

% IMPORTANT
% Because of the script author's coding limitations, each rat must have 
% exactly 6 session folders.

% aacarey Sept 2015

%% WHAT DO YOU WANT THIS SCRIPT TO DO?

cfg = [];

% Where to send the data and diary?
cfg.output_fd = 'D:\My_Documents\TmazePaper\data'; 

% Should I load the 5's?
cfg.load_questionable_cells = 1;

% Would you like to save the data and the diary?
cfg.writeData = 1; 
cfg.writeDiary = 1; 

% Customize your filenames (same for data and diary)
cfg.prefix = ''; % prepend to filename
cfg.output_fn = 'nPlaceCellsLR'; % 'nPlaceCellsLR'
cfg.suffix = ''; % append to filename. 

%%

% Which rats to include?
cfg.rats = {'R042','R044','R050','R064'}; % recommended not to change {'R042','R044','R050','R064'}

if cfg.writeDiary % save command window text
    cd(cfg.output_fd)
    diary([cfg.prefix,cfg.output_fn,cfg.suffix,'.txt'])
    cd(cfg.output_fd)
end

% set up LoadSpikes' config
please = [];
please.load_questionable_cells = cfg.load_questionable_cells;
please.useClusterFile = 0;

disp('%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%')
disp(' ')
disp(datestr(now)); disp(' ') % show me the date and the time i ran this
disp('   The following data include these rats: '); disp(cfg.rats)
disp('%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%')

originalFolder = pwd; % remember where we started

% Make something to collect each rat's session counts into. s1 is session 1
% and it will hold the number of place cells from that session.
empty = struct('s1',[],'s2',[],'s3',[],'s4',[],'s5',[],'s6',[],'total',[]);

TotalAllRatsL = 0; % grand number of place cells for experiment
TotalAllRatsR = 0; 

% go through each rat and collect the data
for iRat = 1:length(cfg.rats);
    
    collect = empty; % make a copy of empty to put stuff into
    totalL = 0; % this will collect the number of units in total for a single rat
    totalR = 0;
    
    disp('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
    disp(['  Data for ',cfg.rats{iRat},':']); 
    disp('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
    
    % give me a list of directories where I can find session data:
    cfg_temp.rats = cfg.rats(iRat);
    fd = getTmazeDataPath(cfg_temp);  
    
    % go through each session and do the thing
    for iFD = 1:length(fd)
        
        cd([fd{iFD},'\files'])
        [~,sessionID,~] = fileparts(fd{iFD});
        disp(' ')
        disp(['SessionID: ',sessionID,' (session #',num2str(iFD),')'])
        load(FindFile('*armPC.mat'))
       
        nL = length(armPC.L.tc.template_idx);
        nR = length(armPC.R.tc.template_idx);
        disp(['n left place cells = ',num2str(nL)])
        disp(['n right place cells = ',num2str(nR)])
        
        
        % collect total cells recorded for all rats
        TotalAllRatsL = TotalAllRatsL + nL;
        TotalAllRatsR = TotalAllRatsR + nR;
        
        % collect total for each rat 
        totalL = totalL + nL;
        totalR = totalR + nR;
        
        % collect cells from each session
        collect.(['s',num2str(iFD)]).L = nL; %  wow eh. 
        collect.(['s',num2str(iFD)]).R = nR;
        collect.(['s',num2str(iFD)]).sessionID = sessionID;
        
        % ^ tells matlab to assign the value to (for ex), empty.s1 for the first file directory
        % ['s',num2str(iFD)] if run, generates s1 or s2 and so on
        
        
    end
    collect.total.L = totalL;
    collect.total.R = totalR; % the total cells recorded for the current rat
    nPC.(cfg.rats{iRat}) = collect; % makes, for example, nUnits.R042 = collect;
    disp(' ')
    disp(['***Total left place cells for ',cfg.rats{iRat},': ',num2str(totalL)]) 
    disp(['***Total right place cells for ',cfg.rats{iRat},': ',num2str(totalR)]); disp(' ')
end

nPC.TotalAllRats.L = TotalAllRatsL;
nPC.TotalAllRats.R = TotalAllRatsR;
nPC.datetime = datestr(now);

disp(' ')
disp('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
disp(['  Total left place cells for all cfg.rats: ',num2str(TotalAllRatsL)])
disp(['  Total right place cells for all cfg.rats: ',num2str(TotalAllRatsR)])
disp('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')

%% Tie loose ends

if cfg.writeDiary; diary off; end

if cfg.writeData
    cd(cfg.output_fd)
    save([cfg.prefix,cfg.output_fn,cfg.suffix],'nPC')
end

cd(originalFolder)