%% replace old SWRfreqs
% or if you add a suffix, a new metadata file is generated that is
% identical to the original, but has different name and freqs (if
% parameters adjusted)
% *** use LoadMetadata3() to load the variable (in case it has a different
% savename that should be specified)

clear
writeFiles = 0; % save the figures generated by SWRfreak()
suffix = ''; %['-',date,'']; % append to savename of new metadata file
metaload.suffix = ''; % config for LoadMetadata3; if the metadata file you want 
                  % to load has a suffix appended

%% check for requisites (don't want it stopping part way through because something is missing)
cfg = []; 
cfg.requireExpKeys = 1;
cfg.ExpKeysFields = {'goodSWR'};
cfg.requireMetadata = 1;
cfg.MetadataFields = {'SWRtimes'};
cfg.requireFiles = 1; % to save figures, if wanted
proceed = checkTmazeReqs(cfg); % make sure we have everything

%% do the thing
cfg = [];
cfg.rats = {'R064'};
if proceed
originalFolder = pwd;
fd = sort(getTmazeDataPath(cfg)); % get all session directories  

    for iFD = 1:length(fd)
        cd(fd{iFD});
        
        % load some stuff
        LoadMetadata3(metaload)
        LoadExpKeys
        cfg.fc = ExpKeys.goodSWR(1);
        csc = LoadCSC(cfg);
        
        % generate spectrum 
        cfg.win1 = 0.06; % 0.06 default (recommended)
        cfg.win2 = [];
        if writeFiles, cfg.showfig = 1; end
        cfg.weightby = 'amplitude'; % amplitude vs power weighting is misnomer
        SWRfreqs = SWRfreak(cfg,metadata.SWRtimes,csc);
   
        % now save  
        metadata.SWRfreqs = SWRfreqs;
        [~,session,~] = fileparts(fd{iFD});
        savename = strcat(session,'-metadata',suffix,'.mat'); % string concatenation
        save(savename,'metadata'); % this saves the specified variables under the given [save]name
        
        if writeFiles && cfg.showfig, cd([fd{iFD},'\files']);
            
            savename = [session,'-SWRfreqs',suffix,'.png'];
            print(gcf,'-r300','-dpng',savename);
            close(gcf);
        end

    end
    cd(originalFolder)
end

%%
clear