%% replace old SWRfreqs
% or if you add a suffix, a new metadata file is generated that is
% identical to the original, but has different name and freqs (if
% parameters adjusted)

clear
writeFiles = 1; % save the figures generated by SWRfreak()
suffix = ''; % append to savename

%% check for requisites (don't want it stopping part way through because something is missing)
cfg = []; 
cfg.requireExpKeys = 1;
cfg.ExpKeysFields = {'goodSWR'};
cfg.requireMetadata = 1;
cfg.MetadataFields = {'SWRtimes'};
cfg.requireFiles = 1; % to save figures, if wanted
proceed = checkTmazeReqs(cfg); % make sure we have everything

%% do the thing
cfg = [];

if proceed

fd = sort(getTmazeDataPath(cfg)); % get all session directories  

    for iFD = 1:length(fd)
        cd(fd{iFD});
        
        % load some stuff
        LoadMetadata
        LoadExpKeys
        cfg.fc = ExpKeys.goodSWR(1);
        csc = LoadCSC(cfg);
        
        % generate spectrum 
        cfg.win1 = 0.07;
        cfg.win2 = [];
        cfg.showfig = 1;
        cfg.weightby = 'amplitude';
        SWRfreqs = SWRfreak(cfg,metadata.SWRtimes,csc);
   
        % now save  
        metadata.SWRfreqs = SWRfreqs;
        [~,session,~] = fileparts(fd{iFD});
        savename = strcat(session,'-metadata.mat',suffix); % string concatenation
        save(savename,'metadata'); % this saves the specified variables under the given [save]name
        
        if writeFiles && cfg.showfig, cd([fd{iFD},'\','files']);
            
            savename = [session,'-SWRfreqs',suffix,'.png'];
            print(gcf,'-r300','-dpng',savename);
            close(gcf);
        end

    end
end