function CompareDetectors(cfg,IVann,TSD1,TSD2,varargin)
%COMPAREDETECTORS Summary of this function goes here
%   Detailed explanation goes here
%
%    CONFIG OPTIONS
%      cfg.bestScore string specifying which score will be used to
%               determine which detector is the best
%          F1 - (default)
%           J - 
%        
%
%    INPUTS
%      IVann - annotated interval data (output from AnnotateIV)
%      TSD1,TSD2,varargin - TSD data (output from a SWR detector function)
%
% aacarey Dec 2017 twilight in Toronto with a dusting of snow

mfun = mfilename;
cfg_def.verbose = 1;
cfg_def.bestScore = 'F1'; % 'F1','J','F2','F0.5'

cfg = ProcessConfig(cfg_def,cfg,mfun);


if cfg.verbose; disp([mfun,': Comparing SWR detectors...this may take a while...']); end

detectorTSDs = {TSD1, TSD2, varargin{:}};
nContestants = length(detectorTSDs);
varname = cell(size(detectorTSDs));
mfunName = varname;
cfg_temp.verbose = cfg.verbose;

for iContestant = 1:nContestants
    ROCdata(iContestant) = GetROCdata(cfg_temp,IVann,detectorTSDs{iContestant});
    bestScores(iContestant) = ScoreROCdata([],ROCdata(iContestant));
    varname{iContestant} = inputname(2 + iContestant); % because we don't care about cfg and IVann
    if isempty(varname{iContestant})
        varname{iConestant} = ['detector #',num2str(iContestant)];
    end
    
    mfunName{iContestant} = detectorTSDs{iContestant}.cfg.history.mfun{end};
    
end

switch cfg.bestScore
    case 'F1'
        [maxScore,maxIndex] = max(bestF1Score);
    case'J'
        [maxScore,maxIndex] = max(bestJScore);
    otherwise
        error('Unrecognized config option specified in cfg.bestScore')
end

fprintf('%s: %s generated by the function %s() is the best\n',mfun,varname{maxIndex},mfunName{maxIndex})

end

